---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#    extra_hosts:
#      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9999"
#    extra_hosts:
#      - "moby:127.0.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    network_mode: host
    depends_on:
      - kafka
    ports:
      - 9021:9021
    volumes: 
      - /tmp/control-center/data:/var/lib/confluent-control-center
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: localhost:2181
      CONTROL_CENTER_BOOTSTRAP_SERVERS: localhost:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2
      CONTROL_CENTER_CONNECT_CLUSTER: http://localhost:8082
#    extra_hosts:
#      - "moby:127.0.0.1"

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    network_mode: host
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: localhost:2181
      APPLICATION_SECRET: letmein
#docker run -it --rm  -p 9000:9000 -e ZK_HOSTS="your-zk.domain:2181" -e APPLICATION_SECRET=letmein sheepkiller/kafka-manager
